### ISSUE TITLE
@pawaitemadisoncollege trying to implement week 9 into my indie project

### ISSUE THREAD

**Issue by fraisbeck** [fraisbeck/FantasyWorldTracker#1]
I'm having difficulties getting my RESTful service to link up.  I'm not sure if it's because of an issue from a previous weeks work that I messed up something but it keeps looping and not giving me an error or loading anything.  I'm not even sure if I have my logger linked up properly because nothing is being printed to my log file to check what's going on.  It's not even linking up to return simple text to the web page like this weeks activity does.

**Comment by pawaitemadisoncollege** [comment]
Hi @fraisbeck - Can you provide a bit more detail here? Which class/method/line of code is looping? Screenshots and links to the relevant code will help me have an idea of what to look at. Include details such as: what do you see if you set a breakpoint and step through the relevant code? Slack #week-9 might be a good way to get a discussion going on this too - often faster than opening an issue as your classmates have visibility into that too (I sometimes don't review issues until my grading window).
